Bugfix : refreshing access token
KoCMoHaBTa/MHIdentityKit pull request #4
Opened 2022-05-19 09:23 UTC by svetzhelev

Refreshing the access token when expires_in is nil from the authorization server.

2022-05-20 04:53 UTC, KoCMoHaBTa requested changes

2022-05-20 04:53 UTC, KoCMoHaBTa commented on MHIdentityKit.xcodeproj/project.pbxproj
> +				9954AE421E9D169700F2A73D /* Headers */,
Why build phases have been reordered?

2022-05-20 04:53 UTC, KoCMoHaBTa commented on MHIdentityKit/Infrastructure/IdentityManager/IdentityManager.swift
> +    func authorize(request: URLRequest, forceAuthenticate: Bool, skipRefresh: Bool, handler: @escaping (URLRequest, Error?) -> Void)
Documentation for `skipRefresh` is missing. This applies to all functions.

2022-05-20 04:53 UTC, KoCMoHaBTa commented on MHIdentityKit/Infrastructure/UserAgent/macOS/WebViewUserAgentViewController.swift
> -//
Why this file is deleted?

2022-05-20 05:19 UTC, KoCMoHaBTa commented
Also there were some compile issue on macOS, that i've fixed, so please rebase from master, otherwise the CI can't compile.

2022-05-26 11:33 UTC, svetzhelev commented on MHIdentityKit.xcodeproj/project.pbxproj
> +				9954AE421E9D169700F2A73D /* Headers */,
With latest xCode order of headers matters, and if not changed on 2nd build a compile error will occur.

2022-05-26 11:34 UTC, svetzhelev commented on MHIdentityKit/Infrastructure/UserAgent/macOS/WebViewUserAgentViewController.swift
> -//
By mistake probably...

2022-05-27 09:05 UTC, svetzhelev commented on MHIdentityKit/Infrastructure/IdentityManager/IdentityManager.swift
> +    func authorize(request: URLRequest, forceAuthenticate: Bool, skipRefresh: Bool, handler: @escaping (URLRequest, Error?) -> Void)
Done.

2022-05-27 09:05 UTC, svetzhelev commented on MHIdentityKit/Infrastructure/UserAgent/macOS/WebViewUserAgentViewController.swift
> -//
Fixed.

2022-06-11 10:23 UTC, closed without merging